[project]
name = "traffic-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "202715235+victortowers@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
[tool.vercel]
entrypoint = "c3:app"

[tool.uv.workspace]
members = [
    "turin_build",
]
