[project]
name = "traffic-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "202715235+victortowers@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "firebase-admin>=7.6.0",
    "numpy>=2.5.2",
    "osmium>=4.3.1",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "scipy>=1.18.1",
    "sqlalchemy>=2.0.54",
    "typing>=3.10.0.0",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
traffic-stuff = "traffic_stuff:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.vercel]
entrypoint = "c3:app"
