steps:

  # 1. Install dependencies + test
  - name: 'python:3.13'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL=/usr/local/bin sh

        uv sync --frozen

  # 2. Download Geofabrik
  - name: 'gcr.io/cloud-builders/curl'
    id: 'download-geofabrik'
    args:
      - '-L'
      - '--fail'
      - '--retry'
      - '5'
      - '-o'
      - '/workspace/sudeste.osm.pbf'
      - 'https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf'

  # 3. Extract
  - name: 'ghcr.io/osmcode/osmium-tool'
    id: 'osmium'
    entrypoint: 'osmium'
    args:
      - extract
      - '--polygon'
      - 'shape.geojson'
      - '--output'
      - '/workspace/sudeste-extract.osm.pbf'
      - '/workspace/sudeste-latest.osm.pbf'

  # 4. Run Python processor
  - name: 'python:3.13'
    id: 'generate-data'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="/root/.local/bin:$$PATH"

        uv sync --frozen
        uv run ruff check .
        uv run mypy .
        python -m py_compile osm14.py

        uv run python osm14.py \
          --with-coords /workspace/sudeste-extract.osm.pbf

options:
  logging: CLOUD_LOGGING_ONLY
