steps:
  # 1. Install dependencies + test
  - name: 'ghcr.io/astral-sh/uv:python3.13-bookworm-slim'
    id: 'test'
    dir: /workspace/turin_build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/traffic-build

        uv sync
        uv run ruff check .
        uv run mypy .
        uv run python -m py_compile osm14.py

  # 2. Download Geofabrik
  - name: 'gcr.io/cloud-builders/curl'
    id: 'download-geofabrik'
    args:
      - '-L'
      - '--fail'
      - '--retry'
      - '5'
      - '-o'
      - '/workspace/turin_build/sudeste.osm.pbf'
      - 'https://r2.turinflow.com.br/sudeste-260923.osm.pbf'

  # 3. Extract
  - name: 'debian:bookworm-slim'
    id: 'osmium'
    dir: '/workspace/turin_build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        apt-get update
        apt-get install -y --no-install-recommends osmium-tool

        osmium --version

        osmium extract \
          --polygon shape.geojson \
          --output /workspace/turin_build/sudeste-extract.osm.pbf \
          /workspace/turin_build/sudeste.osm.pbf

  # 4. Run Python processor
  - name: 'ghcr.io/astral-sh/uv:python3.13-bookworm-slim'
    id: 'generate-data'
    dir: '/workspace/turin_build/'
    entrypoint: 'bash'
    secretEnv:
        - 'R2_ACCESS_KEY'
        - 'R2_SECRET_ACCESS_KEY'
    args:
        - '-c'
        - |
          set -e

          apt update && apt install -y libexpat1
          uv sync
          uv tree
          uv run python osm14.py \
            --with-coords \
            sudeste-extract.osm.pbf

          uv tool install awscli

          export AWS_ACCESS_KEY_ID="$$R2_ACCESS_KEY"
          export AWS_SECRET_ACCESS_KEY="$$R2_SECRET_ACCESS_KEY"
          export AWS_DEFAULT_REGION="auto"

          aws s3 sync /workspace/turin_build/.osm_cache s3://turin-data1/ --endpoint-url "https://a5682a7c9f2732888eedbc7c0071c76c.eu.r2.cloudflarestorage.com"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/R2_ACCESS_KEY/versions/latest
      env: R2_ACCESS_KEY

    - versionName: projects/$PROJECT_ID/secrets/R2_SECRET_ACCESS_KEY/versions/latest
      env: R2_SECRET_ACCESS_KEY
