name: Build and Publish Docker container

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turin_graph

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked

      - name: Download Application Data
        working-directory: ./turin_graph
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto

        run: mkdir -p .osm_cache && aws s3 sync "s3://${{ secrets.R2_BUCKET}}" .osm_cache --endpoint-url "${{ secrets.R2_ENDPOINT }}" && dir -a

      - name: Build container
        working-directory: ./turin_graph
        run: docker build -t turin-container:latest .

      - name: Start services
        working-directory: ./turin_graph
        run: docker compose up -d

      - name: Debug container
        run: |
          docker compose ps
          docker compose logs --no-color traffic-test
          sleep 5
          docker compose ps
          docker compose logs --no-color traffic-test

      - name: Wait for API
        run: |
          timeout 10 bash -c \
            'until curl -fsS http://localhost:8080/openapi.json > /dev/null; do sleep 1; done'

      - uses: schemathesis/action@v3
        with:
          schema: 'http://localhost:8080/openapi.json'
          authorization: 'Bearer ${{ secrets.API_TOKEN }}'
          args: '--report json'

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: schemathesis-results
          path: schemathesis-report/
          retention-days: 7

      - name: Cleanup
        if: always()
        run: docker compose down

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
